# @package _global_

# run with `--multirun hydra=spectra_data_sweep` flag
hydra:
  sweeper:
    params:
      data.sparsification_prob: 0.0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9
      data.replicates: range(${repeats})