hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      data.sparsification_prob: 0.1, 0.2
      data.replicates: range(${repeats})
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - hydra=spectra_data_sweep
  job:
    name: train
    chdir: null
    override_dirname: hydra=spectra_data_sweep
    id: ???
    num: ???
    config_name: train.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/aaronw/Desktop/PhD/Research/QMUL/Research/scBench
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/aaronw/Desktop/PhD/Research/QMUL/Research/scBench/configs
      schema: file
      provider: main
    - path: hydra_plugins.hydra_colorlog.conf
      schema: pkg
      provider: hydra-colorlog
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      debug: null
      local: default
      hparams_search: null
      experiment: null
      hydra: spectra_data_sweep
      extras: default
      paths: default
      trainer: cpu
      logger: null
      callbacks: default
      model: gears
      data: perturb
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
task_name: train
tags:
- dev
train: true
test: true
ckpt_path: null
seed: null
repeats: 3
data:
  _target_: src.data.perturb_datamodule.PertDataModule
  data_dir: ${paths.data_dir}
  data_name: replogle_k562
  batch_size: 32
  spectra_parameters:
    number_repeats: 3
    random_seed:
    - 42
    - 44
    - 46
    sparsification_step: 0.1
    force_reconstruct: true
  sparsification_prob: 0.0
  replicates: 0
  num_workers: 0
  pin_memory: false
model:
  _target_: src.models.gears_module.GEARSLitModule
  net:
    _target_: src.models.reproduction.gears.gears.GEARSNetwork
    hidden_size: 64
    num_go_gnn_layers: 1
    num_gene_gnn_layers: 1
    decoder_hidden_size: 16
    num_similar_genes_go_graph: 20
    num_similar_genes_co_express_graph: 20
    coexpress_threshold: 0.4
    uncertainty: false
    uncertainty_reg: 1
    direction_lambda: 0.1
    G_go: null
    G_go_weight: null
    G_coexpress: null
    G_coexpress_weight: null
    no_perturb: false
    pert_emb_lambda: 0.2
    num_genes: 5045
    num_perts: 9853
  pertmodule:
    _target_: src.data.perturb_datamodule.PertDataModule
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.001
    weight_decay: 0.0005
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 1
    gamma: 0.5
  model_name: gears
  compile: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: best_model_at_epoch_{epoch:03d}
    monitor: null
    verbose: false
    save_last: true
    save_top_k: 1
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 20
  accelerator: cpu
  devices: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  deterministic: false
paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  data_dir: ${paths.root_dir}/data/splits/perturb
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: false
  enforce_tags: true
  print_config: true
