_target_: src.models.prediction_module.PredictionModule

net:
  _target_: src.models.components.predictors.MLP
  in_dim: ${eval:'${emb_dim}*2'}
  hidden_dim: 256
  out_dim: ${total_genes}
  num_layers: 1

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-3
  weight_decay: 0.0

criterion:
  _target_: torch.nn.MSELoss


scheduler: null # set this in experiment config


