# @package _global_

defaults:
  - _self_
  - data: perturb
  - model: null # must be specified in experiment
  - callbacks: default
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: cpu
  - paths: default
  - extras: null
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

task_name: "test"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "test"
